Update dependencies
underscoreio/cats-seed.g8 pull request #8
Opened 2021-08-01 09:38 UTC by sh0hei

2022-08-23 06:37 UTC, yourzbuddha approved these changes
Looks good!

2022-08-23 06:37 UTC, yourzbuddha commented
@sh0hei is it gonna be merged?

2022-08-23 06:42 UTC, yourzbuddha requested changes

2022-08-23 06:42 UTC, yourzbuddha commented on project/build.properties
> +sbt.version=1.5.5
You can use 1.7.1

2022-08-24 08:32 UTC, merged

2022-08-24 08:32 UTC, noelwelsh commented
Thanks!